
services:

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - base-fastapi:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432

volumes:
  base-fastapi:
